### ISSUE TITLE
Error when running APK docs

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apk#26]
**Description:
The following error appears when trying to run the APK docs locally using the `npm run dev` command.

```
wso2@mariangela docs-apk-veupress-branch % npm run dev


> apk-docs@0.0.610 predev
> set NODE_OPTIONS=--openssl-legacy-provider && vuepress check-md docs


Checking markdown...
Checking passed


> apk-docs@0.0.610 dev
> set NODE_OPTIONS=--openssl-legacy-provider && vuepress dev docs

wait Extracting site metadata...
tip Apply local theme at /Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/docs/.vuepress/theme...
tip Apply theme local ...
warning An error was encountered in plugin "@mr-hope/last-update"
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @mr-hope/comment (i.e. "@mr-hope/vuepress-plugin-comment") ...
tip Apply plugin @mr-hope/reading-time (i.e. "@mr-hope/vuepress-plugin-reading-time") ...
tip Apply plugin @mr-hope/components (i.e. "@mr-hope/vuepress-plugin-components") ...
tip Apply plugin @mr-hope/seo (i.e. "@mr-hope/vuepress-plugin-seo") ...
tip Apply plugin @mr-hope/sitemap (i.e. "@mr-hope/vuepress-plugin-sitemap") ...
tip Apply plugin @mr-hope/git (i.e. "@mr-hope/vuepress-plugin-git") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin clean-urls (i.e. "vuepress-plugin-clean-urls") ...
tip Apply plugin md-enhance (i.e. "vuepress-plugin-md-enhance") ...
tip Apply plugin named-chunks (i.e. "vuepress-plugin-named-chunks") ...
tip Apply plugin photo-swipe (i.e. "vuepress-plugin-photo-swipe") ...
tip Apply plugin smooth-scroll (i.e. "vuepress-plugin-smooth-scroll") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin tabs (i.e. "vuepress-plugin-tabs") ...
tip Apply plugin check-md (i.e. "vuepress-plugin-check-md") ...
tip Apply plugin chunkload-redirect (i.e. "vuepress-plugin-chunkload-redirect") ...
tip Apply plugin @xiaopanda/code-copy (i.e. "@xiaopanda/vuepress-plugin-code-copy") ...
tip Apply plugin vuepress-default-canonical ...
tip Apply plugin robots (i.e. "vuepress-plugin-robots") ...

● Client █████████████████████████ compiling (0%)  
 

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /apk/docs/
ℹ ｢wds｣: Content not from webpack is served from /Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/docs/.vuepress/public
ℹ ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/webpack/lib/NormalModule.js:503:5
    at /Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/webpack/lib/NormalModule.js:358:12
    at /Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Volumes/Case-Sensitive/APK/APK-DOCS-V2/docs-apk-veupress-branch/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.0

```

**Comment by Mariangela** [comment]
Closing this issue as it was fixed with https://github.com/wso2/docs-apk/pull/27
